
export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST';
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS';
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL';


export const QUESTION_LEVEL_LIST_REQUEST = 'QUESTION_LEVEL_LIST_REQUEST';
export const QUESTION_LEVEL_LIST_SUCCESS = 'QUESTION_LEVEL_LIST_SUCCESS';
export const QUESTION_LEVEL_LIST_FAIL = 'QUESTION_LEVEL_LIST_FAIL';

export const QUESTION_TYPE_LIST_REQUEST = 'QUESTION_TYPE_LIST_REQUEST';
export const QUESTION_TYPE_LIST_SUCCESS = 'QUESTION_TYPE_LIST_SUCCESS';
export const QUESTION_TYPE_LIST_FAIL = 'QUESTION_TYPE_LIST_FAIL';

export const QUESTION_ADD_REQUEST = 'QUESTION_ADD_REQUEST';
export const QUESTION_ADD_SUCCESS = 'QUESTION_ADD_SUCCESS';
export const QUESTION_ADD_FAIL = 'QUESTION_ADD_FAIL';